server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teicommerce
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: always
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: jwtSecret
  # time in hours
  expiration: 0.5
  refreshExpiration: 4320
