server:
  port: 8080
  error:
    include-message: always
    whitelabel:
      enabled: false

spring:
  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    url: jdbc:mysql://localhost:3306/teicommerce
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: always
    hibernate:
      ddl-auto: update
    show-sql: true

  web:
    resources:
      add-mappings: false

jwt:
  secret: jwtSecret
  # time in hours
  expiration: 20
  refreshExpiration: 259200
